name:                text-cursor
version:             0.1.0.0
github:              "shubhamjagdhane/text-cursor"
license:             BSD3
author:              "Shubham Jagdhane"
maintainer:          "shubhamjagdhane1010@gmail.com"
copyright:           "2023 Shubham Jagdhane"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/text-cursor#readme>

dependencies:
- base >= 4.7 && < 5
- validity
- text
- genvalidity-hspec
- hspec

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  text-cursor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text-cursor

tests:
  text-cursor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text-cursor
